### ISSUE TITLE
Add an encoding to the feed

### ISSUE THREAD

**Issue by spinningarrow** [michelle/bulog#1]
When I added your blog's feed to my feed reader (feedly, in case you were wondering) it came up as "blog.michellebu.com - Michelle&#39;s blog". I'm guessing it's because the feed source is missing an encoding. If you just change the first line of your `rss.xml` from

```
<?xml version="1.0"?>
```

to

```
<?xml version="1.0" encoding="utf-8"?>
```

it should be fine.

**Comment by michelle** [comment]
Ah I see, thanks for pointing that out :).
